cmake_minimum_required(VERSION 3.16)
project(qca_crypto_bench LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
find_package(PkgConfig REQUIRED)
pkg_check_modules(QCA REQUIRED IMPORTED_TARGET qca3-qt6)
find_package(OpenSSL 3 REQUIRED COMPONENTS Crypto)
add_executable(qca_crypto_bench main.cpp)
target_link_libraries(qca_crypto_bench PRIVATE PkgConfig::QCA OpenSSL::Crypto)
find_package(OpenSSL 3.2 REQUIRED COMPONENTS SSL Crypto)
add_executable(qca_dtls_bench dtls.cpp)
target_link_libraries(qca_dtls_bench PRIVATE PkgConfig::QCA OpenSSL::SSL OpenSSL::Crypto)
