<qconf>
 <name>Iris</name>
 <profile>iris.pro</profile>
 <noprefix/>
 <lib/>
 <moddir>qcm</moddir>
 <dep type='qt42'>
  <required/>
 </dep>
 <dep type='buildmode'>
  <required/>
 </dep>
 <dep type='universal'>
  <required/>
 </dep>
 <dep type='idn'>
  <required/>
 </dep>
 <dep type='qca'>
  <required/>
 </dep>
 <dep type='zlib'>
  <required/>
 </dep>
 <dep type='extra'>
  <required/>
 </dep>
 <dep type='qjdns'>
  <required/>
 </dep>
 <dep type='b2'>
  <required/>
 </dep>
</qconf>
