cmake_minimum_required(VERSION 3.2.0)
option(IRIS_NETNAMES_DEBUG "Add -DNETNAMES_DEBUG definition" OFF)
option(IRIS_PSI_ENABLE_SCTP_DEBUG "Add -DPSI_ENABLE_SCTP_DEBUG definition" OFF)
option(IRIS_ICE_DEBUG "Add -DICE_DEBUG definition" OFF)
option(IRIS_PROX_DEBUG "Add -DPROX_DEBUG definition" OFF)
option(IRIS_BS_DEBUG "Add -DBS_DEBUG definition" OFF)
option(IRIS_S5B_DEBUG "Add -DS5B_DEBUG definition" OFF)
option(IRIS_IBB_DEBUG "Add -DIBB_DEBUG definition" OFF)
option(IRIS_SM_DEBUG "Add -DIRIS_SM_DEBUG definition" OFF)
option(IRIS_XMPP_DEBUG "Add -DXMPP_DEBUG definition" OFF)
option(IRIS_TESTDEBUG_H "Add -DTESTDEBUG_H definition" OFF)
if(IRIS_NETNAMES_DEBUG)
    add_definitions(-DNETNAMES_DEBUG)
endif()
if(IRIS_PSI_ENABLE_SCTP_DEBUG)
    add_definitions(-DPSI_ENABLE_SCTP_DEBUG)
endif()
if(IRIS_ICE_DEBUG)
    add_definitions(-DICE_DEBUG)
endif()
if(IRIS_PROX_DEBUG)
    add_definitions(-DPROX_DEBUG)
endif()
if(IRIS_BS_DEBUG)
    add_definitions(-DBS_DEBUG)
endif()
if(IRIS_S5B_DEBUG)
    add_definitions(-DS5B_DEBUG)
endif()
if(IRIS_IBB_DEBUG)
    add_definitions(-DIBB_DEBUG)
endif()
if(IRIS_SM_DEBUG)
    add_definitions(-DIRIS_SM_DEBUG)
endif()
if(IRIS_XMPP_DEBUG)
    add_definitions(-DXMPP_DEBUG)
endif()
if(IRIS_TESTDEBUG_H)
    add_definitions(-DTESTDEBUG_H)
endif()
