name: Nix CI

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  nix-build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Install Nix
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            system-features = nixos-test benchmark big-parallel kvm

      - name: Test Nix build on ${{ matrix.os }}
        run: |
          ver=$(git tag --contains "$(git rev-parse @)" | head -1)
          if [[ -z $ver ]]; then ver=git-$(git rev-parse --short @); fi
          nix-build --argstr version "$ver" -o result-ci-test-"$ver"-build-on-${{ matrix.os }}
